# Generated by Django 4.1.7 on 2023-03-11 08:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام شهر')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام کشور')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام دانشگاه')),
                ('acronym', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='image/uni_logo', verbose_name='لوگو')),
                ('type', models.CharField(choices=[('private', 'خصوصی'), ('non_private', 'غیرخصوصی')], max_length=50, verbose_name='نوع')),
                ('overview', models.TextField()),
                ('established_year', models.DateField(verbose_name='سال تاسیس')),
                ('number_of_students', models.IntegerField(verbose_name='تعداد کل دانشجو')),
                ('number_of_international_students', models.IntegerField(verbose_name='تعداد کل دانشجویان بین المللی')),
                ('url_uni_address', models.URLField(verbose_name='لینک سایت دانشگاه')),
                ('acceptance_rate', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='ریت پذیرش')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_module.city')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_module.country'),
        ),
    ]
